### ISSUE TITLE
ARCore 개발 환경 구축하기 

### ISSUE THREAD

**Issue by hemil0102** [hemil0102/GumamdongAR#2]
SPM를 통해 ARCore를 설치하고 구글 샘플 예제를 실행한다.

**Comment by hemil0102** [comment]
Geospatial Anchor 예제를 돌려보는 중입니다. 
- 국내에서 Streetscape, Terrain, Rooftop 모드에서 Localization까지는 수행을 하지만, Raycast를 통해서 앵커 생성이 되지 않는 부분을 확인했습니다. 
- Mesh가 형성된 부분에 대해서는 앵커가 생성되는 것을 확인했습니다. 
- 결과적으로 구글의 VPS 기반 앵커는 생성할 수 없지만, Elevation API를 통해 고도를 가져오고, 지도에서 위도 경도를 맵 선택을 통해서 앵커를 생성하면 현실 세계 위치에 앵커가 생성될지 궁금해졌습니다.

**Comment by jongfeel** [comment]
2024-10-15 멘토링 때 얘기한 내용 정리

- 회사에서 작업을 해서 휴대폰에 넣어서 보여줌
- 소스 코드는 repository에 공유가 되어야 함

진행 내용에 대한 기록을 조금씩 할 필요가 있음

**Comment by jongfeel** [comment]
- https://github.com/hemil0102/DeveloperStudy/discussions/168

**Comment by hemil0102** [comment]
2024.10.16(수) 
- Xcode 프로젝트 파일을 생성했습니다. 
- Info.plist 설정 
   : Privacy Camera, Location 관련 설정 추가 
   :Linker - General에서 Other Linker Flags에 Obj-c 설정 추가함
- ARCore를 추가하였는데 디펜던시는 프로젝트에 추가가 안된 것으로 보임 (확인 필요) 
   없을 시에 최신 버전 1.46 기준으로 설치
   
특이 사항이 없을 경우 메인에 머지하겠습니다.

**Comment by jongfeel** [comment]
branch를 만드셨으니 pull request 생성 후 merge 하는 방식으로 하면 좋겠습니다.
