### ISSUE TITLE
이미지 마커에 3D 객체 생성하기

### ISSUE THREAD

**Issue by hemil0102** [hemil0102/GumamdongAR#8]
이미지 마커에 3D 객체 생성하기
- 카메라와 인식 이미지 사이에 3D 객체를 배치
   : 정육면체 3D 모델링 생성
   : 정육면체 3D 모델링 배치

**Comment by hemil0102** [comment]
2024.10.27 
1. 문서 스터디 
- https://github.com/hemil0102/DeveloperStudy/discussions/186

2. 이미지를 인식하면 아래 그림처럼 정육각형을 증강 (버튼이 아닌 자동 생성)
<img src = https://github.com/user-attachments/assets/67cd1575-1e06-4237-a28e-b8d764041297 width = 300>

# 질문 
1. 3D ModeEntity를 MeshResource와 Material을 지정해서 생성하였는데, 큐브가 파란색으로 설정을 했음에도 검정색으로 보여서 빛 반사 때문일까 isMetalic을 true에서 false로 변경하였는데, false에서는 이미지를 인식해도 큐브가 생성이 안되는데 왜 이럴까요? 

2. 이미지를 인식하면 큐브가 생성되는데, 이미지 위에 고정 시키고 싶은데 카메라를 움직이면 위치가 변경됩니다. 무엇을 살펴보면 좋을까요?

**Comment by jongfeel** [comment]
1. 아마 light와 관련이 있을 것으로 예상됩니다. 빛이 없으면 shader, material 설정해도 안보이거든요

2. 제 예상에는 image anchor가 아닌 그냥 cube 생성을 한 것 같습니다. image 인식을 하면 cube만 생성되게 한 부분만 있는거죠. ImageAnchor 코드와 함께 image tracking할 때 따라가도록 하는 부분이 따로 있습니다. 그걸 추가해 보면 좋을 것 같습니다.

**Comment by hemil0102** [comment]
2024.11.04(Mon) 
기존에 추적이 안되던 문제를 해결 
원인1: Resource 파일에 이미지 크기 설정에서 센티미터를 미터로 설정하여서 증강된 객체가 작아서 보이지 않음 
원인2: //anchorEntity.transform = Transform(matrix: imageAnchor.transform) 이 줄이 불필요  해당 줄로 인해서 잘못된 트랜스폼이 형성됨, 불필요한 코드 삭제 

최종적으로 아래 코드로 해결 
```Swift 
        func session(_ session: ARSession, didAdd anchors: [ARAnchor]) {
            for anchor in anchors {
                if let imageAnchor = anchor as? ARImageAnchor {
                    if let model = createMarker() {
                        print(imageAnchor)
                        let anchorEntity = AnchorEntity(anchor: imageAnchor)
                        //anchorEntity.transform = Transform(matrix: imageAnchor.transform) 이 줄이 불필요
                        anchorEntity.addChild(model)
                        ARViewController.shared.arView.scene.addAnchor(anchorEntity)
                    }
                }
            }
        }
```
